### ISSUE TITLE
UX: Review dataset description markdown

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1179] opened 2018-06-06 04:08 UTC
### Problem description
It either works really well or breaks down the visual design of the dataset page. Review this.

**Comment by adamzerella** [comment] 2018-06-12 23:37
@tkeuneman I believe this is now a duplicate of https://github.com/TerriaJS/magda/issues/1149, which has a PR in

**Comment by aneesha09** [comment] 2018-08-22 07:11
Done

**Closed by aneesha09** 2018-08-22 07:11 UTC
