### ISSUE TITLE
Records do not return members in the `group` aspect, in a consistent order.

### ISSUE THREAD

**Issue by soyarsauce** [magda-io/magda#2571] opened 2019-10-30 02:01 UTC
**Describe the bug**
For @mwu2018 / @kring 
Records do not return members in the `group` aspect, in a consistent order, when adding new members to a (group)record that has existed for a while (~15 minutes observed)

**To Reproduce**

1. PUT a new record (used as a group)
2. PUT new records, note its IDs
3. Update the first (group) record, and add the IDs to the `group` (terria-magda-versions aspect)
3(b) (Wait a while? Approx ~15 minutes & could reproduce - there's some time aspect to this)
4. Repeat steps 2 & 3 with new records after some time has passed, making sure to add the new records to the _end_ of the array for the `members` key under the group aspect.

**Expected behavior**
When you request the (group) record, observe different `members` ordering returned whether you add a `dereference=true` flag or not.

**Screenshots**
### Dereferenced
![dereferenced](https://user-images.githubusercontent.com/9134432/67822943-4a3e6980-fb15-11e9-89fa-6fa4335a73b4.png)
### No dereference
![no-dereference](https://user-images.githubusercontent.com/9134432/67822945-4a3e6980-fb15-11e9-97cd-59045659733c.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
This is observed in the portal-connected-magda, (doesn't seem to affect the non-portal-ified saas.terria.io version), so it's possibly the connectors doing something strange.

**Comment by kring** [comment] 2019-11-01 03:51
Example of dereference returning a different order:
https://nsw.dt.terria.io/api/v0/registry/records/898a860a-1422-45e9-9de2-bfbc6a4d88bc?aspect=group
versus
https://nsw.dt.terria.io/api/v0/registry/records/898a860a-1422-45e9-9de2-bfbc6a4d88bc?aspect=group&dereference=true

Another:
https://nsw.dt.terria.io/api/v0/registry/records/3c6b4e3d-bf37-4580-acca-0a9c64608e4b?aspect=group
versus
https://nsw.dt.terria.io/api/v0/registry/records/3c6b4e3d-bf37-4580-acca-0a9c64608e4b?aspect=group&dereference=true

**Comment by kring** [comment] 2019-11-01 10:31
This is fixed in https://github.com/TerriaJS/magda/commit/bc2c9810d828132f9e8cc84973425a303c899fae and deployed to nsw.dt.terria.io.

The cause of the bug is that `jsonb_agg` does not guarantee any particular order unless you include an `order by` clause. So the fix uses `with ordinality` to include an index column when the JSON array of indices is turned into a "table", and then the `jsonb_agg` is ordered by that index column.

**Closed** 2019-11-25 00:49 UTC
Labels: bug
