### ISSUE TITLE
Mobile: recent search does not dismiss

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1464] opened 2018-07-17 04:56 UTC
### Problem description
When I type in a search, the recent search still shows even though the search has run. Clicking away does not make it go away.
The next time I use the search, the recent search isn't showing at all.

### Problem reproduction steps
Tested on Android - Google Pixel 
1. Type in a search. You should see the recent history and it's not dismissable
2. Try to run another search. For me, the recent history was then gone
3. This also shows when I click on an organisation from the search results

### Expected:
- Clicking outside should dismiss the recent search
- Earlier recent search was working fine. Please restore to that!

### Screenshot / Design / File reference
![screenshot_20180717-145109](https://user-images.githubusercontent.com/2201814/42797222-93c26040-89d1-11e8-83a1-2b2832048491.png)
![screenshot_20180717-145343](https://user-images.githubusercontent.com/2201814/42797223-93eb4a8c-89d1-11e8-9448-59f49906b460.png)

**Comment by t83714** [comment] 2018-07-18 23:00
Hi @tkeuneman 
I am having some trouble to reproduce this issue (I am using the android emulator: Target Device is google Pixel 1 ).
For me, I did have some reason to dismiss the recent search. But it's because of the small screen size --- once the soft keyboard popup, there is no too much blank space you can click to dismiss the recent search. 
--- the softkeyboard took half of the screen. And If click the area near the logo and `DATA.GOV.AU` text, it will take me to the homepage. Therefore, probably the only safe way for me to dismiss the recent search is to click the `humburger` button.
My question is: Which particular blank area you tried to click to make the recent search go away (and it didn't go away)?
![image](https://user-images.githubusercontent.com/674387/42911953-61ec609c-8b30-11e8-89c7-28afc98a9050.png)

**Comment by t83714** [comment] 2018-07-19 03:37
Thanks a lot, @tkeuneman ~
Find it's a little bit hard to reproduce this.
Close it now and we can re-open it if we come across this issue again.

**Closed by t83714** 2018-07-19 03:37 UTC
Labels: bug, priority: showstopper
