### ISSUE TITLE
More details on organisation

### ISSUE THREAD

**Issue by chloeleichen** [magda-io/magda#1389] opened 2018-07-09 00:19 UTC
### Problem description
Details required in https://github.com/magda-io/magda/issues/1322

currently, we have:

```
description:"Australian Bureau of Statistics - SA Data Released
imageUrl: "https://data.sa.gov.au/data/uploads/group/2017-01-11-044253.549195abslogowh2.gif"
name: "abs-sa-data"
title: "ABS (SA Data)"
```

### Problem reproduction steps
https://dev.magda.io/api/v0/registry/records/org-sa-774dc75c-cfce-4040-bd52-d3893dc71090?aspect=organization-details

**Comment by AlexGilleran** [comment] 2018-07-09 04:41
Duplicate of https://github.com/magda-io/magda/issues/1360

**Closed by AlexGilleran** 2018-07-09 04:41 UTC
