### ISSUE TITLE
Launceston spatial items crash browser

### ISSUE THREAD

**Issue by simongis** [magda-io/magda#897] opened 2018-05-01 23:24 UTC
### Problem description
When opening up any of the Launceston items that reference endpoints from their ArcGIS Open Data site, this crashes the browser.  Have replicated with Chrome on iOS and Chrome 66 on Windows.

I note that if I open the VicRoads items (which also come from an ArcGIS Open Data site), these preview fine.  One difference is that Launceston serve their services up from a 10.4.1 ArcGIS Server and have the OGC WMS/WFS endpoints enabled, whereas VicRoads services are coming directly from ArcGIS Online and do not have OGC capabilities enabled.

### Problem reproduction steps

Open the following (or any of the items from Launceston)
https://search.data.gov.au/dataset/ds-launceston-http%3A%2F%2Fopendata.launceston.tas.gov.au%2Fdatasets%2F9dde05eb82174fa3b1fcf89299d959a9_2/details?q=launceston%20fence

 
### Extra Info:
I work over at Esri Australia and have done some work in the past with PiaW/TobyB/AllanB/AlexS on helping get Esri shops register their ArcGIS Open Data sites with data.gov.au for harvesting.  I think TobyB helped make some changes on the data.gov.au side to ensure items from ArcGIS Open Data sites would flow through correctly to National Map.  If you feel the issue is on the Esri side, let me know and I can coordinate with the Open Data team over in California.

**Comment by simongis** [comment] 2018-05-01 23:28
I stand corrected, can replicate with this VicRoads item:

https://search.data.gov.au/dataset/ds-vic-7828521c-fc37-4328-9185-78059c6f38ce/details?q=Vicroads%20crash

![image](https://user-images.githubusercontent.com/2769383/39498375-23a9d756-4deb-11e8-9e3c-11ef39c1b16f.png)

**Comment by kring** [comment] 2018-05-02 10:57
Thanks for the report @simongis!

@t83714, it looks like the problem with the first link, at least, is that the map previewer is trying to show a large GeoJSON file. That's surprising because the dataset has both a WMS and an ArcGIS MapServer endpoint, and either of those are likely to work better than the GeoJSON.  Digging a little deeper, it looks like it's choosing GeoJSON because both the WMS and ArcGIS distributions are marked as broken links: https://search.data.gov.au/api/v0/registry/records/ds-launceston-http%3A%2F%2Fopendata.launceston.tas.gov.au%2Fdatasets%2F9dde05eb82174fa3b1fcf89299d959a9_2?aspect=dataset-linked-data-rating&aspect=dcat-dataset-strings&aspect=dataset-quality-rating&aspect=dataset-distributions&dereference=true

The links appear to be working now, though, so maybe the server was just failing to respond when the broken link sleuther last checked?

**Comment by t83714** [comment] 2018-05-03 00:26
@kring Thanks for your analysis. I think you are right we should try to use WMS or ArcGIS source over GeoJSON.  Although this particular case was caused by outdated, I think there are other issues yet to fix:
- MagdaCatalogItem only uses `downloadUrl` and ignore `accessUrl`.  accessUrl should be used when download url is not available.
- ArcGIS / Esri Rest API support is not turned on and this moment

I will create a separate issue for this.

**Comment by t83714** [comment] 2018-05-08 07:25
In order to solve this, we need:
- [ ] `format-sleuther` improvement
- [ ] `MagdaCatalogItem` changes
- [ ] Update `MagdaCatalogItem` for terriaJs
- [ ] Re-run `broken link sleuther`

**Comment by t83714** [comment] 2018-05-08 07:37
Created PR for terrisJS project:
https://github.com/TerriaJS/terriajs/pull/2962

**Comment by steve9164** [comment] 2018-06-19 05:56
Looking at registry records [here](https://search.data.gov.au/api/v0/registry/records/ds-launceston-http%3A%2F%2Fopendata.launceston.tas.gov.au%2Fdatasets%2F9dde05eb82174fa3b1fcf89299d959a9_2?aspect=dataset-distributions&dereference=true) 
- the ESRI MapServer returns a 405 (Bad Method) probably because the specified link is not a valid MapServer request
- the WMS server returns a 400 error because it doesn't like the `HEAD` request

**Comment by simongis** [comment] 2018-06-19 10:08
Let me know if I can help troubleshoot any issues on the Esri side.  
Which specific endpoint gives you a 405? 
I get all good for both [WMS ](http://mapping.launceston.tas.gov.au/arcgis/services/Public/DetailSurvey/MapServer/WMSServer?request=GetCapabilities&service=WMS)and [GeoServices ](http://mapping.launceston.tas.gov.au/arcgis/rest/services/Public/DetailSurvey/MapServer?f=jsapi)endpoints.

**Comment by t83714** [comment] 2018-06-20 00:59
@simongis 
Thanks for your comments.
We have a backend program to test endpoints liveness by sending an HTTP `HEAD` request to the URL.
Here we use `HEAD` method in order to receive a response without the HTTP body for performance consideration.
The endpoint we tested is `http://mapping.launceston.tas.gov.au/arcgis/rest/services/Public/DetailSurvey/MapServer/2`
I think the reason

**Comment by AlexGilleran** [comment] 2018-06-20 01:13
While we should probably be more permissive on the magda side - maybe fall back to `GET` but don't bother downloading the whole thing?

@simongis it'd probably still be good in general if Esri supported HEAD - I'm not sure what a general purpose server is and whether Esri counts as one but [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.1) says:

> All general-purpose servers MUST support the methods GET and HEAD.
> All other methods are OPTIONAL

**Comment by simongis** [comment] 2018-06-20 04:16
Have messaged Launceston GIS admin.  That endpoint is hosted on their infrastructure so expecting it to be a web server configuration issue.

**Comment by aneesha09** [comment] 2018-08-22 07:29
We have updated Launceston URL and have automatic recrawling for broken links. Closing this.

**Closed by aneesha09** 2018-08-22 07:29 UTC
Labels: priority: medium
